FROM node:22 AS build

WORKDIR /build

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:22 AS serve

COPY --from=build /build /build
COPY --from=build /build/dist /app

WORKDIR /app

EXPOSE 3030

# Start the application
CMD ["node", "dist/src/main.js"]