FROM node:22 AS build

WORKDIR /build

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:22 AS serve

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts

COPY --from=build /build/dist ./dist

EXPOSE 3030

CMD ["node", "dist/src/main.js"]
